"""
Compiler service.

Compiles Algorand Python code to TEAL assembly via the PuyaPy compiler.
Handles compilation, TEAL validation, and error reporting.
Returns TEAL code along with ARC-32 and ARC-56 JSON specs generated by Puya.
"""

from __future__ import annotations

from app.middleware.error_handler import AppException
from app.models.schemas import CompileResponse
from app.utils.logger import get_logger
from app.utils.sandbox import compile_algorand_python

logger = get_logger(__name__)

# Sanity limit on TEAL *source text* size.
# NOTE: The 8 KiB AVM limit applies to compiled bytecodes, NOT to human-
# readable TEAL text.  TEAL text is typically 3-10x larger than bytecodes.
# We set a generous 128 KiB sanity cap on the text; the actual bytecode
# size is validated at deploy time by the Algorand node.
_MAX_TEAL_TEXT_SIZE = 128 * 1024


class CompilerService:
    """Compiles Algorand Python source into TEAL assembly via PuyaPy."""

    # ── Compilation ───────────────────────────────────────────

    def compile_algorand_python(self, algorand_python_code: str) -> CompileResponse:
        """
        Compile Algorand Python code via PuyaPy and return TEAL + ARC-32/ARC-56.

        Raises AppException on any failure.
        """
        if not algorand_python_code or not algorand_python_code.strip():
            raise AppException(
                status_code=400,
                error_code="EMPTY_INPUT",
                message="Algorand Python code must not be empty.",
            )

        result = compile_algorand_python(algorand_python_code)

        if not result.success:
            raise AppException(
                status_code=400,
                error_code="COMPILATION_FAILED",
                message=result.error,
                details={
                    "traceback": result.traceback if result.traceback else "",
                    "error_line": result.error_line,
                    "error_column": result.error_column,
                    "error_type": result.error_type,
                    "raw_stderr": result.raw_stderr,
                    "raw_stdout": result.raw_stdout,
                },
            )

        # Validate the produced TEAL
        self._validate_teal(result.approval_teal, label="approval")
        self._validate_teal(result.clear_teal, label="clear")

        return CompileResponse(
            success=True,
            contract_name=result.contract_name,
            teal_code=result.approval_teal,   # backward compat alias
            approval_teal=result.approval_teal,
            clear_teal=result.clear_teal,
            arc32_json=result.arc32_json,
            arc56_json=result.arc56_json,
            approval_program_size=len(result.approval_teal.encode("utf-8")),
            clear_program_size=len(result.clear_teal.encode("utf-8")),
            compilation_warnings=result.compilation_warnings,
        )

    # ── TEAL Validation ──────────────────────────────────────

    @staticmethod
    def _validate_teal(teal: str, label: str = "program") -> None:
        """
        Perform basic sanity checks on compiled TEAL.

        Raises AppException if validation fails.
        """
        if not teal or not teal.strip():
            raise AppException(
                status_code=400,
                error_code="COMPILATION_FAILED",
                message=f"Compiled {label} TEAL is empty.",
            )

        if not teal.lstrip().startswith("#pragma version"):
            raise AppException(
                status_code=400,
                error_code="COMPILATION_FAILED",
                message=f"Compiled {label} TEAL does not start with '#pragma version'.",
            )

        size = len(teal.encode("utf-8"))
        if size > _MAX_TEAL_TEXT_SIZE:
            raise AppException(
                status_code=400,
                error_code="TEAL_TOO_LARGE",
                message=f"{label.title()} TEAL source text is unreasonably large ({size} bytes). Simplify the contract.",
            )

        logger.debug("TEAL validation passed  label=%s  text_size=%d", label, size)
